[[req_core_collections-collectionid-keys-keyfieldid-get-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success*
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The content of that response SHALL be based on the <<collections_collectionid_keys_keyfieldid_schema,Collection's Key Field Schema>>.
|===

===== Parameter Limit

The number of returned key values depends on the server and the value of the `limit` parameter. 

The client can request a limit to the number of key values returned in a response by using the `limit` parameter. The `limit` parameter indicates the maximum number of key values which should be included in a single response.

The server may have a default value for the limit and a maximum limit.

[[req_core_collections-collectionid-keys-keyfieldid-get-success-limit-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success-limit-response*
^|A |If the `limit` parameter is provided by the client and supported by the server, then the response SHALL not contain more resources than specified by the `limit` parameter.
^|B |If the service specifies a maximum value for the `limit` parameter, the response SHALL not contain more resources than this maximum value.
|===

[[req_core_collections-collectionid-keys-keyfieldid-get-success-limit-unsupported]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success-limit-unsupported* 
^|A |If the `limit` parameter is provided by the client but it is not supported by the server, then the server SHALL process the request as if the parameter had not been provided.
|===

===== Paged response

If the number of items in the `keys` array of the response is less than or equal to the requested/default/maximum limit then the server will include a link to the next set of results.

[[per_core_collections-collectionid-keys-keyfieldid-get-success-server-limit]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/core/collections-collectionid-keys-keyfieldid-get-success-server-limit*
^|A |If a server is configured with a maximum response size, then the server MAY page responses which exceed that threshold.
|===

[[req_core_collections-collectionid-keys-keyfieldid-get-success-server-limit]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/collections-collectionid-keys-keyfieldid-get-success-server-limit*
^|A |Clients SHOULD be prepared to handle a paged response even if they have not specified a `limit` parameter in their query.
|===

The effect of the `limit` parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first page. Additional pages can be accessed through hyperlink navigation.

[[rec_core_collections-collectionid-keys-keyfieldid-get-success-next-1]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/collections-collectionid-keys-keyfieldid-get-success-next-1*
^|A |A `200`-response SHOULD include a link to the next "page" (relation: `next`), if more resources have been selected than returned in the response.
|===

[[rec_core_collections-collectionid-keys-keyfieldid-get-success-next-2]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/collections-collectionid-keys-keyfieldid-get-success-next-2*
^|A |Dereferencing a `next` link SHOULD return additional resources from the set of selected resources that have not yet been returned.
|===

[[rec_core_collections-collectionid-keys-keyfieldid-get-success-next-3]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/collections-collectionid-keys-keyfieldid-get-success-next-3*
^|A |The number of resources in a response to a `next` link SHOULD follow the same rules as for the response to the original query and again include a `next` link, if there are more resources in the selection that have not yet been returned.
|===

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

[[per_core_collections-collectionid-keys-keyfieldid-get-success-prev]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/core/collections-collectionid-keys-keyfieldid-get-success-prev*
^|A |A response to a `next` link MAY include a `prev` link to the resource that included the `next` link.
|===

If the server response does not contain all of the key values that match the selection parameters, then the client must be informed of that fact.

[[per_core_collections-collectionid-keys-keyfieldid-get-success-paged-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success-paged-response* 
^|A |If the number of key values in the `keys` element is less than the number that match the selection paarameters, then the `numberMatched` and `numberReturned` properties SHALL be included in the response.
|===

The `numberMatched` property of the response indicates the number of key values that are available in the server that match the selection parameters in the request.

[[per_core_collections-collectionid-keys-keyfieldid-get-success-numberMatched]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success-numberMatched* 
^|A |If a property `numberMatched` is included in the response, the value SHALL be identical to the number of hosted key values that meet the selection parameters provided by the client.
^|B |A server MAY omit this information in a response, if the information about the number of matching resources is not known or difficult to compute.
|===

The number of key values included in a response may be a subset of the number matched. In that case, the `numberReturned` property of the response indicates the number of key values returned in this "page" of the response.

[[per_core_collections-collectionid-keys-keyfieldid-get-success-numberReturned]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collections-collectionid-keys-keyfieldid-get-success-numberReturned* 
^|A |If a property `numberReturned` is included in the response, the value SHALL be identical to the number of items in the `keys` array in the response document.
^|B |A server MAY omit this information in a response, if the information about the number of resources in the response is not known or difficult to compute.
|===