[[rc_core]]
== Requirements Class "Core"
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/core
|Target type |Web API
|Dependency |<<ogcapi-common-part1,OGC 19-072 (OGC - API - Common: Part 1)>>
|Dependency |<<ogcapi-common-part2,OGC 20-024 (OGC - API - Common: Part 2)>>
|Dependency |<<rfc2616,RFC 2616 (HTTP/1.1)>>
|Dependency |<<rfc2818,RFC 2818 (HTTP over TLS)>>
|Dependency |<<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>>
|Dependency |<<rfc7578,RFC 7578 Returning Values from Forms: multipart/form-data>>
|Dependency |<<rfc8288,RFC 8288 (Web Linking)>>
|===

[[core-overview]]
=== Overview

The core requirements class contains the following functionalities: 

The `Landing page` (path `/`) provides an entry point to the API. It contains links to:

* The `API definition` (link relations `service-desc` and `service-doc`).
* The `Conformance declaration` (path `/conformance`, link relation `http://www.opengis.net/def/rel/ogc/1.0/conformance`).
* The `Collections` (path `/collections`, link relation `http://www.opengis.net/def/rel/ogc/1.0/data`).
* The `Joins` (path `/joins`, link relation `joins`).

The `API definition` describes the capabilities of the server that can be used by clients to connect to the server or by development tools to support the implementation of servers and clients. Accessing the `API definition` using HTTP GET returns a description of the API. The API definition can be hosted on the API server(s) or a separate server.

The `Conformance declaration` states the conformance classes from standards or community specifications, identified by a URI, that the API conforms to. Clients can but are not required to use this information. Accessing the `Conformance declaration` using HTTP GET returns the list of URIs of conformance classes implemented by the server.

Accessing the `Collections` using HTTP GET returns a the list of datasets that are available on the server. 

Each `Collection` element in the Collections list can be accessed further in order to get the metadata on each indivual Collection by making an HTTP GET request at path `/collections/{collectionId}`.

Accessing the `Collection's Key Fields` using HTTP GET at path `/collections/{collectionId}/keys` provides information on the key fields of a Collection.

Accessing the `Collection's Key Field` using HTTP GET at path `/collections/{collectionId}/keys/{keyFieldId}` provides the key values of the specific key field. The data joining is executed through these key values.

Accessing the `Joins` using HTTP GET returns a the list of Joins that are available on the server. 

New `Joins` can be created by making a HTTP POST query to the path `/joins`. This is done by joining attribute data from inputted attribute data file with the Collection available on the server. Attribute data can be also joined directly with inputted spatial data files. 

Each `Join` element in the Joins list can be accessed further in order to get the metadata on each indivual Join by making an HTTP GET request at path `/joins/{joinId}`.

Each `Join` can be updated fully by meking a HTTP PUT request to path `/joins/{joinId}`. This is done by joining attribute data from inputted attribute data file with the Collection available on the server.

Each `Join` can be deleted by making a HTTP DELETE request to path `/joins/{joinId}`.

The core module contains support for:

* CSV format for the inputted attribute data files.
* GeoJSON format for the inputted spatial data files.

The <<core-overview-table,Table 2>> contains an overview of the operations specified in the core module.

include::requirements/core_operations_overview.adoc[]

=== HTTP 1.1
[[req_core_http]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/http* 
^|A |The server SHALL conform to <<rfc2616,HTTP 1.1.>>
^|B |If the API supports HTTPS, then the API SHALL also conform to <<rfc2818,HTTP over TLS>>.
|===

=== HTTP Status Codes

<<http_status_codes,Table 3>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[[http_status_codes]]
.Typical HTTP status codes
[width="100%",cols="1,6"]
|===
^|*Status code*|*Description*
^|200 |	A successful request.
^|201 |	The request was executed successfully and it resulted in one or more resources that were created.
^|204 |	A request was executed successfully and there is no additional content in the response payload body.
^|302 |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
^|303 |	The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed. 
^|304 |	An entity tag was provided in the request and the resource has not changed since the previous request.
^|307 |	The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
^|308 |	Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
^|400 |	The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
^|401 |	The request requires user authentication. The response includes a WWW-Authenticate header field containing a challenge applicable to the requested resource.
^|403 |	The server understood the request, but is refusing to fulfill it. While status code 401 indicates missing or bad authentication, status code 403 indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
^|404 | The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
^|405 |	The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
^|406 |	Content negotiation failed. For example, the Accept header submitted in the request did not support any of the media types supported by the server for the requested resource.
^|500 |	An internal error occurred in the server.
|===

The return status codes described in <<http_status_codes,Table 3>> do not cover all possible conditions. See <<rfc7231,IETF RFC 7231>> for a complete list of HTTP status codes.

[[per_core_additional-status-codes]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/core/additional-status-codes* 
^|A |Servers MAY implement additional capabilities provided by the HTTP protocol. Therefore, they MAY return status codes in addition to those listed in <<http_status_codes,Table 3>>.
|===

When the server encounters an error during the processing of the request , the server may wish to include information in addition to the status code in the response. Since Web API interactions are often machine-to-machine, a machine-readable report would be preferred. <<rfc7807,IETF RFC 7807>> addresses this need by providing "Problem Details" response schemas for both JSON and XML.

[[rec_core_problem_details]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/problem-details* 
^|A |The server SHOULD include a "problem details" report in any error response in accordance with <<rfc7807, IETF RFC 7807>>.
|===

=== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

[[rec_core_cross-origin]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/cross-origin* 
^|A |If the server is intended to be accessed from a browser, cross-origin requests SHOULD be supported. Note that support can also be added in a proxy layer on top of the server.
|===

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]

* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

include::requirements/core_operations.adoc[]