[[media_types]]
== Media Types

JSON media types that would typically be supported by a server that supports JSON are:

* `application/geo+json` for joined data outputs, and

* `application/json` for all other resources.

The typical HTML media type for all "web pages" in a server would be `text/html`.

=== Joined Dataset Outputs

[[req_core_joined-dataset-outputs]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/joined-dataset-outputs*
^|A |The server implementations SHALL support the media type  `application/geo+json` as the format for the joined dataset outputs.
^|B | The server implementations MAY support any other media type the as the format for the joined dataset outputs.
|===

=== Problem Details Media Types
[[rec_core_problem_details_media_type]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/problem-details-media-type*
^|A |The server implementations SHOULD support for the RFC 7807 Problem Details response body the media type '`application/problem+json`.
|===