[[rc_encodings]]
== Requirements Classes for Encodings
[[encodings-overview]]
=== Overview

This clause specifies three requirements classes for encodings to be used by the OGC API - Joins implementations. 

* <<requirements_class_html, HTML>>

* <<requirements_class_json, JSON>>

* <<requirements_class_geojson, GeoJSON>>

The support for the JSON encoding class is mandatory and the support for HTML encoding class is recommended.
The support for the GeoJSON format for the joined data output is mandatory.  

[[requirements_class_html]]
==== Requirements Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML has two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web,

* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in document <<spatial_data_on_the_web, Spatial Data on the Web Best Practices>>. This standard therefore recommends supporting HTML as an encoding.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/html
|Target type |Web API
|Dependency |<<rc_core,Requirements Class "Core">>
|Dependency |<<html5,HTML5>>
|Dependency |<<schema.org,Schema.org>>
|===

[[req_encodings_html-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/html/definition* 
^|A |Every `200`-response of an operation of the server SHALL support the media type `text/html`.
|===

[[req_encodings_html-content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/html/content* 
^|A |Every `200`-response of the server with the media type `text/html` SHALL be a <<html5,HTML5 document>> that includes the following information in the HTML body:

* All information identified in the schemas of the link:https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#responseObject[Response Object]. in the HTML `<body/>`, and

* All links in HTML `<a/>` elements in the HTML `<body/>`.
|===

[[rec_schema-org]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/html/schema-org* 
^|A |A `200`-response with the media type `text/html`, SHOULD include Schema.org annotations.
|===

[[requirements_class_json]]
==== Requirements Class "JSON"

JSON is a text syntax that facilitates structured data interchange between programming languages. It is commonly used for Web-based software-to-software interchanges. The support for JSON is mandatory for OGC API - Joins implementations.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/json
|Target type |Web API
|Dependency |<<rc_core,Requirements Class "Core">>
|Dependency |<<rfc8259,IETF RFC 8259: The JavaScript Object Notation (JSON) Data Interchange Format>>
|Dependency |<<json-schema,JSON Schema>>
|===

[[req_encodings_json-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/json/definition* 
^|A |Every `200`-response of an operation of the server SHALL support the media type `application/json`.
|===

[[req_encodings_json-content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/json/content* 
^|A |Every `200`-response with the media type `application/json` SHALL include, or link to, a payload encoded according to the <<rfc8259, JSON Interchange Format>>.
^|B |The schema of all responses with the media type `application/json` SHALL conform with the JSON Schema specified for that resource.
|===

[[requirements_class_geojson]]
==== Requirements Class "GeoJSON"

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/geojson
|Target type |Web API
|Dependency |<<rc_core,Requirements Class "Core">>
|Dependency |<<rfc8259,IETF RFC 8259: The JavaScript Object Notation (JSON) Data Interchange Format>>
|Dependency |<<rfc7946,GeoJSON>>
|===

[[req_encodings_geojson-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/geojson/definition* 
^|A |The server SHALL support the GeoJSON format for the joined data outputs.
|===
