[[per_data_joining_joins-get-op]]

[permission]
====
[%metadata]
identifier:: /per/data-joining/joins-get-op
part:: 
--
The server MAY support the query parameter `limit` to limit the number of resources that can be returned in a single response. The `limit` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):
----
name: limit
in: query
required: false
schema:
  type: integer
  minimum: 1
  maximum: 1000
  default: 10
----
Note: The values for minimum, maximum and default are only examples and MAY be changed.
--

--
The server MAY support the query parameter `datetime` to filter the returned joins by their execution timestamp.
The `datetime` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):
----
name: datetime
in: query
required: false
schema:
  type: string
----
Temporal geometries are either a date-time value or a time interval. The parameter value SHALL conform to the following syntax (using link:https://tools.ietf.org/html/rfc2234[ABNF]):
----
interval-closed     = date-time "/" date-time
interval-open-start = "../" date-time
interval-open-end   = date-time "/.."
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
----
The syntax of date-time is specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].

Open ranges in time intervals at the start or end are supported using a double-dot (..) or an empty string for the start/end..
--
====