[[ats_data_joining_collections-collectionid-get-success]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-joining/collections-collectionid-get-success
target:: /req/data-joining/collections-collectionid-get-success
test-purpose:: Validate that the Collection content complies with the required structure and contents.
test-method::
+
--
FOR each Collection document, validate:

. That the Collection document includes an `id` property.
. Validate that any extent properties included in the Collection document complies with test <<req_data_joining_collections-collectionid-get-success-extent,/conf/data-joining/collections-collectionid-get-success-extent>>.
. Validate that the Collection document complies with test <<ats_data_joining_collections-collectionid-get-success-links, /conf/data-joining/collections-collectionid-get-success-links>>
. Validate the content of the Collection document for all supported media types using the <<collections_collectionid_schema, Collection schema>> and test <<ats_json-json-content, /conf/json/json-content>>.
. Verify that the content of the response is consistent with the content for this Resource Collection in the `/collections` response. That is, the values for `id`, `title`, `description` and `extent` are identical.
--
====