[[ats_data_joining_joins-get-success]]

[abstract_test]
====
[%metadata]
identifier:: /conf/data-joining/joins-get-success
target:: /req/data-joining/joins-get-success
test-purpose:: Validate that the joins content complies with the required structure and contents.
test-method::
+
--
. Validate that the response document complies with <<joins_schema, Joins Schema>>.

. Validate that the response document complies with test <<ats_data_joining_joins-get-success-limit,/conf/data-joining/joins-get-success-limit>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-limit-unsupported,/conf/data-joining/joins-get-success-limit-unsupported>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-datetime,/conf/data-joining/joins-get-success-datetime>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-paged-response,/conf/data-joining/joins-get-success-paged-response>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-numberMatched,/conf/data-joining/joins-get-success-numberMatched>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-numberReturned,/conf/data-joining/joins-get-success-numberReturned>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-items,/conf/data-joining/joins-get-success-items>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-links,/conf/data-joining/joins-get-success-links>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-items-links,/conf/data-joining/joins-get-success-items-links>>
. Validate that the response document complies with test <<ats_data_joining_joins-get-success-timeStamp,/conf/data-joining/joins-get-success-timeStamp>>
--
====