[[ats_data_joining_joins-post-op]]
[abstract_test]
====
[%metadata]
identifier:: /conf/data-joining/joins-post-op
target:: /req/data-joining/joins-post-op
test-purpose:: 
. Validate that data can be joined from an inputted data file with a Collection available on the server from the expected location.
. If the server supports the direct GeoJSON output functionality, validate that data can be joined from the expected location from an inputted data file with a Collection available on the server with a direct GeoJSON output.
test-method::
+
--
Test method for (1): +
1. Issue an HTTP POST request to the URL `{root}/joins` where: +
- The request contains the header: `Content-Type: multipart/form-data;` +
- The form data parameter `right-dataset-format` has the value `http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-csv`. +
- The form data parameter `collection-id` has the same value as `id` property of a collection (from query `{root}/collections`). +
- The form data parameter `output-formats` has the value `http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output-geojson`. +
- The request contains either the uploaded intput data file or it is referenced via a URL. +
- Other query parameters are set correctly. +
2. Validate that a document was returned with a status code `201`. +
3. Validate the contents of the returned document using test <<ats_data_joining_joins-post-success, /conf/data-joining/joins-post-success>>

Test method for (2): +
1. Issue an HTTP POST request to the URL `{root}/joins` where: +
- The request contains the header: `Content-Type: multipart/form-data;` +
- The form data parameter `right-dataset-format` has the value `http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-csv`. +
- The form data parameter `collection-id` has the same value as `id` property of a collection (from query `{root}/collections`). +
- The form data parameter `output-formats` has the value `http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output-geojson-direct`. +
- The request contains either the uploaded intput data file or it is referenced via a URL. +
- Other query parameters are set correctly. +
2. Validate that a document was returned with a status code `200`. +
3. Validate the contents of the returned document using test <<ats_data_joining_joins-post-success, /conf/data-joining/joins-post-success>>
--
====