[requirement,type="general",id="/req/core/filejoin-post-op",label="/req/core/filejoin-post-op",obligation="requirement"]
[[req_core_filejoin-post-op]]
====
[.component,class=part]
--
If the server implements __file joining operations__ the implementation SHALL support the HTTP POST operation at path `{root}/filejoin`.
--

[.component,class=part]
--
The request is made as a <<rfc7578,multipart/form-data>> request. 

The request SHALL contain the header:

* Content-Type: multipart/form-data;
--

[.component,class=part]
--
If the left dataset file is uploaded with the query, it SHALL contain the header:

* Content-Disposition: form-data; filename="[left dataset file's name]"; name="left-dataset-file";
--

[.component,class=part]
--
The server SHALL support the GeoJSON format for the left dataset. The parameters of that request are listed in section B.
--

[.component,class=part]
--
If the right dataset file is uploaded with the query, it SHALL contain the header

* Content-Disposition: form-data; filename="[right dataset file's name]"; name="right-dataset-file";
--

[.component,class=part]
--
The input data files SHALL be encoded with the `UTF-8` encoding.
--

[.component,class=part]
--
The Form Data parameters of the query are listed in a <<req_core_filejoin-post-op-form-data-parameters,Table 7>>:
--
====