[requirement,type="general",id="/req/core/collections-collectionid-keys-keyfieldid-get-op",label="/req/core/collections-collectionid-keys-keyfieldid-get-op",obligation="requirement"]
[[req_core_collections-collectionid-keys-keyfieldid-get-op]]
====
[.component,class=part]
--
If the server implements the __data joining operations__ operation set it SHALL support the HTTP GET operation at the path `{root}/collections/{collectionId}/keys/{keyFieldId}`.
--

[.component,class=part]
--
The parameter collectionId is each `id` property in the `collections` response (JSONPath: `$.collections[*].id`).
--

[.component,class=part]
--
The parameter `keyFieldId` is each `id` property in the `collection's key fields` response (JSONPath: `$.keys[*].id`).
--

[.component,class=part]
--
The server MAY support the query parameter `key` to filter the results by key value. 	
The `key` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):
----
name: key
in: query
required: false
schema:
  type: string
----
--

[.component,class=part]
--
The server MAY support the query parameter `limit` to limit the number of key values that can be returned in a single response.

The `limit` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):
----
name: limit
in: query
required: false
schema:
  type: integer
  minimum: 1
  maximum: 10000
  default: 1000
----
Note The values for minimum, maximum and default are only examples and MAY be changed.
--
====