[[requirements_class_data-joining]]

[requirements_class]
.Data Joining
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/data-joining
subject:: Web API
inherit:: <<requirements_class_core,Requirements Class: Core>>
inherit:: <<requirements_class_input-file-upload,Requirements Class: Input File Upload>>
inherit:: <<requirements_class_input-http-ref,Requirements Class: File Referencing with URL>>
inherit:: <<requirements_class_input-csv,Requirements Class: CSV File Input>>
inherit:: <<requirements_class_output-geojson,Requirements Class: GeoJSON Output for Joined Data>>
inherit:: <<requirements_class_output-geojson-direct,Requirements Class: Direct GeoJSON Output for Joined Data>>
inherit:: <<OGC20-024,OGC 20-024 (OGC - API - Common: Part 2)>>
inherit:: <<rfc2616,RFC 2616 (HTTP/1.1)>>
inherit:: <<rfc2818,RFC 2818 (HTTP over TLS)>>
inherit:: <<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>>
inherit:: <<rfc7578,RFC 7578 Returning Values from Forms: multipart/form-data>>
inherit:: <<rfc8288,RFC 8288 (Web Linking)>>
requirement:: /req/data-joining/collections-get-op
requirement:: /req/data-joining/collections-get-success
requirement:: /req/data-joining/collections-get-success-links
requirement:: /req/data-joining/collections-get-success-items
requirement:: /req/data-joining/collections-collectionid-get-op
requirement:: /req/data-joining/collections-collectionid-get-success
requirement:: /req/data-joining/collections-collectionid-get-success-extent   
requirement:: /req/data-joining/collections-collectionid-get-success-links
requirement:: /req/data-joining/collections-collectionid-keys-get-op
requirement:: /req/data-joining/collections-collectionid-keys-get-success
requirement:: /req/data-joining/collections-collectionid-keys-get-success-default-key
requirement:: /req/data-joining/collections-collectionid-keys-get-success-links
requirement:: /req/data-joining/collections-collectionid-keys-get-success-items-links
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-op
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-limit
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-limit-unsupported
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-paged-response
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-numberMatched
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-numberReturned
requirement:: /req/data-joining/collections-collectionid-keys-keyfieldid-get-success-links
requirement:: /req/data-joining/joins-get-op
requirement:: /req/data-joining/joins-get-success
requirement:: /req/data-joining/joins-get-success-limit
requirement:: /req/data-joining/joins-get-success-limit-unsupported
requirement:: /req/data-joining/joins-get-success-datetime
requirement:: /req/data-joining/joins-get-success-paged-response
requirement:: /req/data-joining/joins-get-success-numberMatched
requirement:: /req/data-joining/joins-get-success-numberReturned
requirement:: /req/data-joining/joins-get-success-items
requirement:: /req/data-joining/joins-get-success-links
requirement:: /req/data-joining/joins-get-success-items-links
requirement:: /req/data-joining/joins-get-success-timeStamp
requirement:: /req/data-joining/joins-post-op
requirement:: /req/data-joining/joins-post-success
requirement:: /req/data-joining/joins-post-success-attribute-data-file-csv-multiple-keys
requirement:: /req/data-joining/joins-post-success-attribute-data-file-csv-attribute-names
requirement:: /req/data-joining/joins-joinid-get-op
requirement:: /req/data-joining/joins-joinid-get-success
requirement:: /req/data-joining/joins-joinid-get-success-links
requirement:: /req/data-joining/joins-joinid-get-success-links-collection
requirement:: /req/data-joining/joins-joinid-get-success-links-outputs
====