.Preface

This document defines the core module of the OGC API - Joins Standard. The OGC API - Joins Standard is a multi-part document that can be extended by specifying extensions modules to the core module.

This Standard originates from the OGC Standard: OpenGIS® Georeferenced Table Joining Service (TJS) Implementation Standard (document nr. <<OGC10-070r2,10-070r2>>), specified in 2010.

This document specifies a service interface that supports join operations between input data files that could be feature collections available on some server or directly using other input files. The core module specifies requirements for CSV and GeoJSON input files.

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

This document specifies the core module of the OGC API - Joins Standard. The OGC API - Joins specifies requirements for a Web API that supports join operation(s) for input data files that could be feature collections available on some server or directly using other input files. 

The API Joins Standard also defines operations for viewing general metadata on the service implementation, metadata and key values on the feature collections, and operations for accessing and deleting the created joins.

Please note that for the purposes of brevity, the OGC API – Joins: Core Standard may be referend to as “the OGC Joins API” or “this document” or “this “Standard”.