[abstract]
== Abstract

This document specifies the core module of the OGC API - Joins Standard. This Standard can be used for online joining of tabular data with some other data, such as geospatial data. The data joining process is executed through common key values that are available in both datasets.

The core module specifies requirements for a Web API that supports following use cases:

* Getting metadata on available collections, their key fields and key values.
* Executing joins between input tabular data files and collections available on some server.
* Accessing the created joins.
* Deleting joins.
* Executing joins between two input files.

The input data files can be either uploaded to the server with the join query or provided by referencing them via URL addresses. The server implementations have a mandatory requirement to support the GeoJSON format for the joined data, and in addition, they can support any other file formats. 
The core module supports CSV format for the input tabular data files. The joining between two input data files is supported between GeoJSON and CSV formats.

Please note that for the purposes of brevity, the OGC API – Joins: Core Standard may be referend to as “the OGC Joins API” or “this document” or “this “Standard”.

== Preface

This document defines the _OGC API - Joins - Part 1: Core_ Standard. The OGC API - Joins Standard is a multi-part document that can be extended by specifying extensions modules to the core module.

This Standard originates from the OGC Standard: OpenGIS® Georeferenced Table Joining Service (TJS) Implementation Standard (document nr. <<OGC10-070r2,10-070r2>>), specified in 2010.

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////


[security_considerations]
== Security Considerations
The part 1 of the OGC API - Joins Standard defines HTTP GET, POST and DELETE operations that can be used for accessing data on the server, sending data to the server and deleting data from the server.
Some server implementations may have also the ability to retrieve data from other sources. Some OGC API — Joins implementations may assign different roles to different users that may result in different abilities to access, create and delete data. The access control can be described in the OpenAPI definition as discussed in OGC API — Common (https://docs.ogc.org/is/19-072/19-072.html#rc_oas30-security). 

The requests made to the server implementations of the OGC API - Joins Standard may take some time to resolve, especially when the input data files are large.
If several of these requests are processed simultaneously, the server implementations can become slow or unresponsive. Servers should set and apply reasonable limits 
to the sizes of the input data files to prevent Denial of Service attacks.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[cols=",",options="header",]
|===
|Name                                  |Affiliation
|Pekka Latvala _(editor)_              |Finnish Geospatial Research Institute FGI, National Land Survey of Finland
|===