[[rc_core]]
== Requirements Class "Core"

include::./requirements/requirements_class_core.adoc[]

[[core-overview]]
=== Overview

The OGC API - Joins core requirements class specifies three operation sets: __discovery operations__, __data joining operations__ and __file joining operations__. <<core-overview-table,Table 4>> contains an overview of the operations specified in the core module.

__Discovery operations__ defines operations for accessing the API landing page, the API definition document, and the information on the server implementation's conformance to the Joins API Standard. 

__Data joining operations__ defines operations for accessing metadata and key values on the feature collections that are available on the server, operations for joining data from input data files with the collections, and operations for accessing and deleting the created joins.

__File joining operations__ defines operations for joining data from input data files directly with other input data files.

The core requirements class specifies the following input data file format support:

* CSV format for the __data joining operations__.
* CSV and GeoJSON format for the __file joining operations__.

include::./requirements/core/REQ_operations.adoc[]

*Overview on the functionalities*

The `Landing page` (path `/`) provides an entry point to the API. It contains links to:

* The `API definition` (link relations `service-desc` and `service-doc`).
* The `Conformance declaration` (path `/conformance`, link relation `http://www.opengis.net/def/rel/ogc/1.0/conformance`).
* The `Collections` (path `/collections`, link relation `http://www.opengis.net/def/rel/ogc/1.0/data`).
* The `Joins` (path `/joins`, link relation `joins`).

The `API definition` describes the capabilities of the server that can be used by clients to connect to the server or by development tools to support the implementation of servers and clients. Accessing the `API definition` using HTTP GET returns a description of the deployed API implementation instance. The API definition can be hosted on the API server(s) or on a separate server.

The `Conformance declaration` states the conformance classes from standards or community specifications, identified by a URI, that the API implementation instance conforms to. Clients can - but are not required to use this information. Accessing the `Conformance declaration` using HTTP GET returns the list of URIs of conformance classes implemented by the server.

Accessing the `Collections` using HTTP GET returns a list of feature collections that are available on the server. 

Each `Collection` element in the Collections list can be accessed further in order to get the metadata on each individual Collection by making an HTTP GET request at path `/collections/{collectionId}`.

Accessing the `Collection's Key Fields` using HTTP GET at path `/collections/{collectionId}/keys` provides information on the key fields of a Collection.

Accessing the `Collection's Key Field` using HTTP GET at path `/collections/{collectionId}/keys/{keyFieldId}` provides the key values of the specific key field. The data joining is executed through these key values.

Accessing the `Joins` using HTTP GET returns a list of Joins that are available on the server. 

New `Joins` can be created by making a HTTP POST query at path `/joins`. This is done by joining data from input data file with a Collection available on the server. 

Each `Join` element in the Joins list can be accessed further in order to get the metadata on each individual Join by making an HTTP GET request at path `/joins/{joinId}`.

Each `Join` can be deleted by making a HTTP DELETE request at path `/joins/{joinId}`.

The data from the input data file can be joined directly with other input data file(s) by making a HTTP POST request at path `/filejoin`.

include::./requirements/core_operations_overview.adoc[]

=== HTTP 1.1
[[req_core_http]]

include::./requirements/core/REQ_http.adoc[]

=== HTTP Status Codes

<<http_status_codes,Table 5>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[[http_status_codes]]
.Typical HTTP status codes
[width="100%",cols="1,6"]
|===
^|*Status code*|*Description*
^|200 |	A successful request.
^|201 |	The request was executed successfully and it resulted in one or more resources that were created.
^|204 |	A request was executed successfully and there is no additional content in the response payload body.
^|302 |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
^|303 |	The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed. 
^|304 |	An entity tag was provided in the request and the resource has not changed since the previous request.
^|307 |	The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
^|308 |	Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
^|400 |	The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
^|401 |	The request requires user authentication. The response includes a WWW-Authenticate header field containing a challenge applicable to the requested resource.
^|403 |	The server understood the request, but is refusing to fulfill it. While status code 401 indicates missing or bad authentication, status code 403 indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
^|404 | The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
^|405 |	The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
^|406 |	Content negotiation failed. For example, the Accept header submitted in the request did not support any of the media types supported by the server for the requested resource.
^|500 |	An internal error occurred in the server.
|===

The return status codes described in <<http_status_codes,Table 5>> do not cover all possible conditions. See <<rfc7231,IETF RFC 7231>> for a complete list of HTTP status codes.

[[per_core_additional-status-codes]]
include::./requirements/core/PER_additional_status_codes.adoc[]

When the server encounters an error during the processing of the request, the server may wish to include information in addition to the status code in the response. Since Web API interactions are often machine-to-machine, a machine-readable report would be preferred. <<rfc7807,IETF RFC 7807>> addresses this need by providing "Problem Details" response schemas for both JSON and XML.

[[problem_details]]
include::./requirements/core/REC_problem_details.adoc[]

=== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

[[cross-origin]]
include::./requirements/core/REC_cross_origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]

* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]


=== API Landing Page

The HTTP GET operation at service root path `{root}/` returns the API landing page document. The API landing page provides a starting point for the use of the API implementation instance and contains links to the:

* API definition document.
* Conformance information.
* Metadata on collections available on the server.
* Joins available on the server.

==== Request

include::./requirements/core/REQ_root-op.adoc[]

==== Response

include::./requirements/core/REQ_root-success.adoc[]

[[landing-page-op]]
===== Response Schema for the  Landing Page
The landing page response is based on the following schema (from <<OGC19-072,OGC - API - Common: Part 1>> document).

include::./../schemas/root_schema.adoc[]

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

[[api-definition-op]]
=== API Definition

Servers SHOULD provide an API Definition resource that describes the capabilities of the server. This resource can be used by client developers to understand the supported services, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

==== Request
include::./requirements/core/REQ_api-definition-op.adoc[]

include::./requirements/core/REC_api-definition-op.adoc[]

==== Response

include::./requirements/core/REQ_api-definition-success.adoc[]

include::./requirements/core/REC_api-definition-oas.adoc[]

==== Error Situations

See <<http_status_codes,HTTP status codes>> for general guidance.


[[conformance-op]]
=== Declaration of Conformance Classes

The HTTP GET operation at path `{root}/conformance` returns a list of conformance classes that the server supports.

==== Request

include::./requirements/core/REQ_conformance-op.adoc[]

==== Response

include::./requirements/core/REQ_conformance-success.adoc[]

===== Response Schema for the Conformance Declaration

The schema for the conformance response is based on the following schema (from <<OGC19-072,OGC API - Common - Part 1>> document).

include::./../schemas/conformance_schema.adoc[]

==== Error Situations

See <<http_status_codes,HTTP status codes>> for general guidance.

[[collections-op]]
=== Collections

The HTTP GET operation at path `{root}/collections` returns metadata on the collections that are available on the server.

==== Request

include::./requirements/core/REQ_collections-get-op.adoc[]

==== Response

include::./requirements/core/REQ_collections-get-success.adoc[]

===== Response Schema for the Collections

The response is based on the following schema (from <<OGC20-024,OGC - API - Common: Part 2>> document).

include::../schemas/collections_schema.adoc[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::./requirements/core/REQ_collections-get-success-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::./requirements/core/REC_collections-get-success-descriptions.adoc[]

The `timeStamp` property of the Collections response indicates when the response was generated.

include::./requirements/core/REQ_collections-get-success-timestamp.adoc[]

The `collections` property of the Collections response provides a description of each individual collection hosted by the server. These descriptions are based on the <<collections_collectionid_schema, Collection Schema>>.

include::./requirements/core/REQ_collections-get-success-items.adoc[]

include::./requirements/core/PER_collections-get-success-items.adoc[]

==== Error Situations

See <<http_status_codes,HTTP status codes>> for general guidance.

[[collection-op]]
=== Collection

The HTTP GET operation at path `{root}/collections/{collectionId}` returns metadata on a specific collection available on the server.

==== Request

include::./requirements/core/REQ_collections-collectionid-get-op.adoc[]

==== Response

include::./requirements/core/REQ_collections-collectionid-get-success.adoc[]

[[response_schema_for_the_collection]]
===== Response Schema for the Collection
The Collection response is based on the following schema (from <<OGC20-024,OGC - API - Common: Part 2>> document).

include::./../schemas/collections_collectionid_schema.adoc[]

[[req_core_collections-collectionid-resource-definition]]

The requirements of the response are originally defined in the http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/collection Requirements Class described in the <<OGC20-024,OGC - API - Common: Part 2>> document.

====== Extent
include::./requirements/core/REQ_rc-md-extent.adoc[]

include::./requirements/core/REC_rc-md-extent.adoc[]

include::./requirements/core/REC_rc-md-extent-single.adoc[]

//[discrete]
====== Item Type

The collections defined by this core module provide information on their key fields and key values.

include::./requirements/core/REC_rc-md-items-type.adoc[]

//[discrete]
====== Links
To support hypermedia navigation, the links property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::./requirements/core/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::./requirements/core/REQ_rc-md-items-descriptions.adoc[]

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

[[collection_key_fields-op]]
=== Collection's Key Fields

The HTTP GET operation at path `{root}/collections/{collectionId}/keys` returns a list of key fields of a specific collection.

==== Request

include::./requirements/core/REQ_collections-collectionid-keys-get-op.adoc[]

==== Response

include::./requirements/core/REQ_collections-collectionid-keys-get-success.adoc[]

=====  Response Schema for the Collection's Key Fields
include::../schemas/collections_collectionid_keys_schema.adoc[]

[[req_core_collections-collectionid-keys-resource-definition]]

//[discrete]
====== isDefault

Information on the Collection's default key field for the data joins. Value `true` indicates the default key field. 

include::./requirements/core/REQ_collections-collectionid-keys-default-key.adoc[]

//[discrete]
====== language

Language in which the key field's key values are written (if applicable to the key field). The format of the language field follows the ISO 639-1 language code values.

//[discrete]
====== id

Identifier of the key field.

//[discrete]
====== links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the collection's key fields' key values.

[[req_core_collections-collectionid-keys-key-values-link]]
Description of the `links` property of the `CollectionKeysResponseObject`:

include::./requirements/core/REQ_collections-collectionid-keys-links.adoc[]

Description of `links` property of the `CollectionKeysObject`:

include::./requirements/core/REQ_collections-collectionid-keys-items-links.adoc[]

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

[[collection_key_field-op]]
=== Collection's Key Field

The HTTP GET operation at path `{root}/collections/{collectionId}/keys/{keyFieldId}` returns a list of key values of a specific key field of a specific collection.

==== Request

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-op.adoc[]

include::./requirements/core/PER_collections-collectionid-keys-keyfieldid-get-op.adoc

==== Response

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success.adoc[]

===== Parameter Limit

The number of returned key values depends on the server and the value of the `limit` parameter. 

The client can request a limit to the number of key values returned in a response by using the `limit` parameter. The `limit` parameter indicates the maximum number of key values which should be included in a single response.

The server may have a default value for the limit and a maximum limit.

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success-limit-response.adoc[]

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success-limit-unsupported.adoc[]

===== Paged response

If the number of items in the `keys` array of the response is less than or equal to the requested/default/maximum limit then the server will include a link to the next set of results.

include::./requirements/core/PER_collections-collectionid-keys-keyfieldid-get-success-server-limit.adoc[]

include::./requirements/core/REC_collections-collectionid-keys-keyfieldid-get-success-server-limit.adoc[]

The effect of the `limit` parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first page. Additional pages can be accessed through hyperlink navigation.

include::./requirements/core/REC_collections-collectionid-keys-keyfieldid-get-success-next-1.adoc[]

include::./requirements/core/REC_collections-collectionid-keys-keyfieldid-get-success-next-2.adoc[]

include::./requirements/core/REC_collections-collectionid-keys-keyfieldid-get-success-next-3.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::./requirements/core/PER_collections-collectionid-keys-keyfieldid-get-success-prev.adoc[]

If the server response does not contain all of the key values that match the selection parameters, then the client must be informed of that fact.

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success-paged-response.adoc[]

The `numberMatched` property of the response indicates the number of key values that are available in the server that match the selection parameters in the request.

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success-numberMatched.adoc[]

include::./requirements/core/PER_collections-collectionid-keys-keyfieldid-get-success-numberMatched.adoc[]

The number of key values included in a response may be a subset of the number matched. In that case, the `numberReturned` property of the response indicates the number of key values returned in this "page" of the response.

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-get-success-numberReturned.adoc[]

include::./requirements/core/PER_collections-collectionid-keys-keyfieldid-get-success-numberReturned.adoc[]

===== Response Schema for the Collection's Key Field
include::./../schemas/collections_collectionid_keys_keyfieldid_schema.adoc[]

[[req_core_collections-collectionid-keys-keyfieldid-resource-definition]]

//[discrete]
====== keys

Array of key objects.

====== numberMatched

The number of key values that are available in the server that match the selection parameters in the request.

====== numberReturned

The number of key values returned in the response.

//[discrete]
====== key

Key value.

//[discrete]
====== links

To support hypermedia navigation, the links property must be populated with sufficient hyperlinks.

include::./requirements/core/REQ_collections-collectionid-keys-keyfieldid-links.adoc[]

//[discrete]
====== title

Human-readable description of the key value.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

If the parameter `keyFieldId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

[[joins-get-op]]
=== Joins

The HTTP GET operation at path `{root}/joins` returns a list of joins that are available on the server.

==== Request

include::./requirements/core/REQ_joins-get-op.adoc[]

include::./requirements/core/PER_joins-get-op.adoc[]

==== Response

include::./requirements/core/REQ_joins-get-success.adoc[]

===== Parameter Limit

The number of returned joins depends on the server and the value of the `limit` parameter. 

The client can request a limit to the number of joins returned in a response by using the `limit` parameter. The `limit` parameter indicates the maximum number of joins which should be included in a single response.

The server may have a default value for the limit and a maximum limit.

include::./requirements/core/REQ_joins-get-success-limit-response.adoc[]

include::./requirements/core/REQ_joins-get-success-datetime.adoc[]

===== Parameter datetime

include::./requirements/core/REQ_joins-get-success-limit-unsupported.adoc[]

===== Paged response

If the number of items in the `joins` array of the response is less than or equal to the requested/default/maximum limit then the server will include a link to the next set of results.

include::./requirements/core/PER_joins-get-success-server-limit.adoc[]

include::./requirements/core/REC_joins-get-success-server-limit.adoc[]

The effect of the `limit` parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first page. Additional pages can be accessed through hyperlink navigation.

include::./requirements/core/REC_joins-get-success-next-1.adoc[]

include::./requirements/core/REC_joins-get-success-next-2.adoc[]

include::./requirements/core/REC_joins-get-success-next-3.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::./requirements/core/PER_joins-get-success-prev.adoc[]

If the server response does not contain all of the joins that match the selection parameters, then the client must be informed of that fact.

include::./requirements/core/REQ_joins-get-success-paged-response.adoc[]

The `numberMatched` property of the response indicates the number of joins that are available in the server that match the selection parameters in the request.

include::./requirements/core/REQ_joins-get-success-numberMatched.adoc[]

include::./requirements/core/PER_joins-get-success-numberMatched.adoc[]

The number of joins included in a response may be a subset of the number matched. In that case, the `numberReturned` property of the response indicates the number of joins returned in this "page" of the response.

include::./requirements/core/REQ_joins-get-success-numberReturned.adoc[]

include::./requirements/core/PER_joins-get-success-numberReturned.adoc[]

===== Response schema for the Joins

include::./../schemas/joins_schema.adoc[]

[[joins-resource-definition]]

//[discrete]
====== joins
The `joins` property of the response provides a description of each individual join hosted by the server.

include::./requirements/core/REQ_joins-get-success-items.adoc[]

//[discrete]
====== links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the joins.

Property `links` in the `JoinsResponseObject`:

include::./requirements/core/REQ_joins-get-success-links.adoc[]

Property `links` in the `JoinsObject`:

include::./requirements/core/REQ_joins-get-success-items-links.adoc[]

//[discrete]
====== id

Identifier of the join.

//[discrete]
====== numberReturned

The number of joins that are available in the server that match the selection parameters in the request.

//[discrete]
====== numberMatched

The number of joins returned in the response.

//[discrete]
====== timeStamp

Property `timeStamp` in the `JoinsResponseObject`:

include::./requirements/core/REQ_joins-get-success-timeStamp.adoc[]

Property `timeStamp` in the `JoinsObject`:

The time when the join was generated.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

[[joins-post-op]]
=== Join Creation

The HTTP POST operation at path `{root}/joins` creates a new join. 

The operation joins data from an input data file with a collection hosted on the server.

The data file can either be uploaded to the server with the query or referenced via URL link.

The joins are executed via common key values that are available in both datasets.

If the input data file contains additional key values that are not available in the collection, they will not be included to the joined output. The extension modules may alter this behavior.

The core module contains support for CSV format for the input data files.

==== Request

include::./requirements/core/REQ_joins-post-op.adoc[]

include::./requirements/core/REQ_joins-post-op-form-data-parameters.adoc[]

include::./requirements/core/PER_joins-post-op.adoc[]

==== Response

include::./requirements/core/REQ_joins-post-success.adoc[]

include::./requirements/core/REQ_joins-post-attribute-data-file-csv-multiple-keys.adoc[]

include::./requirements/core/REQ_joins-post-success-attribute-data-file-csv-attribute-names.adoc[]

===== Response schema for the Join Creation

The response schema for queries that create a join resource is expressed with the <<join_schema,Join Schema>>.

For responses that produce a GeoJSON output, the response is a GeoJSON file that contains also the joined attributes.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

[[join-get-op]]
=== Join

The HTTP GET operation at path `{root}/joins/{joinId}` returns metadata on a specific join that is available on the server.

==== Request

include::./requirements/core/REQ_joins-joinid-get-op.adoc[]

==== Response

include::./requirements/core/REQ_joins-joinid-get-success.adoc[]

===== Response Schema for the Join

include::./../schemas/join_schema.adoc[]

[[req_core_joins-joinid-resource-definition]]

//[discrete]
====== links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks.

include::./requirements/core/REQ_joins-joinid-links.adoc[]

//[discrete]
====== join

The metadata on the join.

//[discrete]
====== id

Unique identifier for the join resource.

//[discrete]
====== timeStamp

The time when the join was generated.

//[discrete]
====== inputs

Input datasets that were used in the join operation.

//[discrete]
====== attributeDataset
Name or URL of the input attribute data file.

//[discrete]
====== collection

A `link` object that contains information on the collection that was used in the join operation.

include::./requirements/core/REQ_joins-joinid-inputs-collection.adoc[]

//[discrete]
====== outputs

Links to the produced outputs that contain the joined data.

include::./requirements/core/REQ_joins-joinid-outputs.adoc[]

//[discrete]
====== joinInformation

Information on the execution of the data join operation

//[discrete]
====== numberOfMatchedCollectionKeys

The number of collection's key values, to which attribute data was joined successfully.

//[discrete]
====== numberOfUnmatchedCollectionKeys

The number of collection's key values, to which attribute data couldn´t be joined.

//[discrete]
====== numberOfAdditionalAttributeKeys

The number of additional key values in the attribute dataset that were not available in the collection.

//[discrete]
====== matchedCollectionKeys

List of collection's key values that were successfully joined with attribute data

//[discrete]
====== unmatchedCollectionKeys

List of collection's key values, to which attribute data couldn´t be joined.

//[discrete]
====== additionalAttributeKeys

List of key values in the attribute data file that were not available in the collection's key field.

//[discrete]
====== duplicateAttributeKeys

List of duplicate keys in the attribute data file.

//[discrete]
====== numberOfDuplicateAttributeKeys

The number of keys in the attribute data file that had duplicate entries.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `joinId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

[[join-delete-op]]
=== Join Delete

The HTTP DELETE operation at path `{root}/joins/{joinId}` deletes the specific join from the server. 

==== Request

include::./requirements/core/PER_joins-joinid-delete-op.adoc[]

==== Response

include::./requirements/core/REQ_joins-joinid-delete-success.adoc[]

===== Response schema for the Join Delete

The response of the operation is empty.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `joinId` does not exist on the server, the status code of the response will be `404`. (see <<http_status_codes,Table 5>>).

[[filejoin-post-op]]
=== File Joining

The HTTP POST operation at path `{root}/filejoin` joins data from input data file directly with another input data file.

The input data files can be either uploaded to the server with the query or referenced via URL links.

The core module supports data joining from the right dataset to the left dataset. 

The core module contains support for:
* The CSV format for the right dataset.
* The GeoJSON format for the left dataset 

The joins are executed via common key values that are available in both datasets. If the right dataset contains additional key values that are not available in the left dataset, they will not be included in the joined output. Extension modules may alter this behavior. 

The result of the operation is the left dataset that contains also the joined attributes from the right dataset.

==== Request

include::./requirements/core/REQ_filejoin-post-op.adoc[]

include::./requirements/core/REQ_filejoin-post-op-form-data-parameters.adoc[]

==== Response

include::./requirements/core/REQ_filejoin-post-success.adoc[]

include::./requirements/core/REQ_filejoin-post-attribute-data-file-csv-multiple-keys.adoc[]

include::./requirements/core/REQ_filejoin-post-success-attribute-data-file-csv-attribute-names.adoc[]

===== Response schema for the File Joining

The response is a GeoJSON file that contains also the joined attributes.

==== Error Situations
See <<http_status_codes,HTTP status codes>> for general guidance.

[[rc_encodings]]
== Requirements Classes for Encodings
[[encodings-overview]]
=== Overview

This clause specifies three requirements classes for encodings to be used by implementations of the OGC API - Joins Standard. 

* <<requirements_class_html, HTML>>

* <<requirements_class_json, JSON>>

* <<requirements_class_geojson, GeoJSON>>

Support for the JSON encoding class is mandatory and support for HTML encoding class is recommended.
Support for the GeoJSON format for the joined data output is mandatory.  

[[requirements_class_html]]
=== Requirements Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML has two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web,

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in document <<SDWBP, Spatial Data on the Web Best Practices>>. The OGC API - Joins Standard therefore recommends supporting HTML as an encoding.

include::./requirements/requirements_class_html.adoc[]

include::./requirements/html/REQ_definition.adoc[]

include::./requirements/html/REQ_content.adoc[]

include::./requirements/html/REQ_schema-org.adoc[]

[[requirements_class_json]]
=== Requirements Class "JSON"

JSON is a text syntax that facilitates structured data interchange between programming languages. It is commonly used for Web-based software-to-software interchanges. The support for JSON is mandatory for OGC API - Joins implementations.

include::./requirements/requirements_class_json.adoc[]

include::./requirements/json/REQ_definition.adoc[]

include::./requirements/json/REQ_content.adoc[]

[[requirements_class_geojson]]
=== Requirements Class "GeoJSON"

include::./requirements/requirements_class_geojson.adoc[]

include::./requirements/geojson/REQ_definition.adoc[]