== Conventions
[[conventions]]

This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
[[identifiers]]

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-joins-1/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations
[[link-relation-types]]
To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> is used.

The link relation types that are used in this document are listed in <<link-relations-table,Table 3>>.

[[link-relations-table]]
.Link Relations.
[width="90%",cols="2,6a"]
|===
2+|The following <<link-relations,registered link relation types [IANA]>> are used in this document:
^|*Link Relation* |*Purpose*
<|alternate | Refers to a substitute for this context.
Refers to a representation of the current resource that is encoded using another media type (the media type is specified in the `type` link attribute).
<|describedby | 
Refers to a resource providing information about the link’s context. +
Links to external resources that further describe the subject resource.
<|license | Refers to a license associated with this context.
<|next | Indicates that the link’s context is a part of a series, and that the next in the series is the link target.
<|prev | Indicates that the link’s context is a part of a series, and that the previous in the series is the link target.
<|self | 
Conveys an identifier for the link's context. +
A link to another representation of this resource.
<|service-desc | 
Identifies service description for the context that is primarily intended for consumption by machines. +
API definitions are considered service descriptions.
<|service-doc | Identifies service documentation for the context that is primarily intended for human consumption.
<|service-meta | Identifies general metadata for the context that is primarily intended for consumption by machines.
2+|In addition, the following link relation types are used for which no applicable registered link relation type could be identified:
^|*Link Relation* |*Purpose*
<|dataset |  Refers to a resource that is comprised of the metadata of the specific collection that is available on the server.
<|conformance | Refers to a resource that identifies the standards that the link's context conforms to.
<|data | Indicates that the link’s context is a distribution of a dataset that is an API and refers to the root resource of the dataset in an API.
<|keys | Refers to a resource that is comprised of metadata of the key fields of the collection represented by the link’s context.
<|key-values | Refers to a resource that is comprised of key values of the collection's key field represented by the link’s context.
<|joins | Refers to a resource that is comprised of the metadata of the created joins that are available on the server.
<|join | Refers to a resource that is comprised of the metadata of the specific join that is available on the server.
<|output |  Refers to an output of the join operation that contains the joined data.
|===

==== Response Schema for the Link Object
[[link_schema]]
The individual hyperlink elements that make up a "links" elements are defined in the https://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/link.yaml[Hyperlink Schema], originally defined in the section 6.3 of the <<OGC19-072, OGC API - Common - Part 1 document>>.

include::./../schemas/link_schema.adoc[]

=== Use of HTTPS

For simplicity, this document generally only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use <<rfc2818,HTTPS>>, not <<rfc2616,HTTP>>.

OGC Web API Standards do not prohibit the use of any valid HTTP option. However, implementers should be aware that optional capabilities that are not in common use could be an impediment to interoperability.