== Conformance
This standard defines the OGC API - Joins core module. The core module specifies three operation sets: __discovery operations__, __data joining operations__ and __file joining operations__. The server implementations are required to support the __discovery operations__ and they must support either one or both of the __data joining operations__ and/or __file joining operations__.

The standardization targets of all conformance classes are "Web APIs."

The __discovery operations__ operation set is represented by the requirements class "<<rc_core,core>>".

The __data joining operations__ operation set is represented by the requirements classes: "<<rc_data_joining,data joining>>" and "<<rc_join_delete,join delete>>". The implementation of the "data joining" requirements class is mandatory, and the implementation of the "join delete" is optional for this operation set, t.

The __file joining operations__ operation set is represented by the requirements class "<<rc_file_joining,file joining>>". 

The imput and output functionalities are represented by the requirement classes: "<<rc_file_uploading_with_query, Input File Upload>>", "<<rc_file_referencing_with_url, File Referencing with URL>>", "<<rc_input_csv, CSV File Input>>", "<<rc_input_geojson,GeoJSON File Input>>", "<<rc_output_geojson,GeoJSON Output for Joined Data>>" and "<<rc_output_geojson_direct, Direct GeoJSON Output for Joined Data>>". The support for CSV input file format is mandatory for the __data joining operations__ and __file joining operations__. The support for the GeoJSON input file format is mandatory for the __file joining operations__.

The encoding formats are represented by requirements classes: "<<rc_json, JSON>>", "<<rc_html, HTML>>" and "<<rc_geojson, GeoJSON>>". 

The JSON encoding format support is mandatory, and the HTML encoding support is recommendedto for the service responses in the __discovery operations__ and __data joining operations__ operation sets. 

The GeoJSON encoding format is mandatory for the joined data output in the __data joining operations__ and as a general output for the __file joining operations__.

The Core requirements class does not mandate any encoding or format for the formal definition of the API. One option is to use the OpenAPI 3.0 specification and OpenAPI 3.0 Requirements Class as defined in the <<OGC19-072,OGC API - Common - Part 1>> document.

=== Summary of conformance URIs

The conformance class URIs defined in this core module are listed in <<conformance_classes_table, Table 1>>.

[[conformance_classes_table]]
.Conformance class URIs.
[width="90%",cols="3,6a",options="header"]
|===
^|*Conformance class*|*URI*
<|<<ats_core,Core>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core
<|<<ats_data_joining,Data Joining>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/data-joining
<|<<ats_join_delete,Join Delete>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/join-delete
<|<<ats_file_joining,File Joining>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/file-joining
2+|*Input*
<|<<ats_input_file_upload,Input File Upload>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-file-upload
<|<<ats_input_http_ref,File Referencing with URL>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-http-ref
<|<<ats_input_csv,CSV File Input>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-csv
<|<<ats_input_geojson,GeoJSON File Input>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-geojson
2+|*Output*
<|<<ats_output_geojson,GeoJSON Output for Joined Data>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output-geojson
<|<<ats_geojson_direct,Direct GeoJSON Output for Joined Data>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output-geojson-direct
2+|*Encodings*
<|<<ats_html,HTML>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/html
<|<<ats_json,JSON>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/json
<|<<ats_geojson,GeoJSON>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/geojson
|===

Conformance with this standard shall be checked using all the relevant tests
specified in <<annex-a,Annex A>> (normative) of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.