== Conformance
This standard defines the OGC API - Joins core requirement class and the encoding requirements classes "JSON", "HTML" and "GeoJSON". 

The standardization targets of all conformance classes are "Web APIs."

The main requirements class is:

* <<rc_core,Core>>.

The core requirements class specifies three operation sets: __discovery operations__, __data joining operations__ and __file joining operations__.

The server implementations are required to support the __discovery operations__ and they must support either one or both of the __data joining operations__ and/or __file joining operations__ <<req_operations,Operations>>.

The CSV input file format is mandatory for the __data joining operations__ and __file joining operations__.

The GeoJSON input file format is mandatory for the __file joining operations__.

The JSON encoding format is mandatory to be supported for service responses. 

The support for HTML encoding format is recommended for service responses.

The GeoJSON encoding is mandatory for the output that contains the joined data in the __data joining operations__ and __file joining operations__.

The Core requirements class does not mandate any encoding or format for the formal definition of the API. One option is to use the OpenAPI 3.0 specification and OpenAPI 3.0 Requirements Class as defined in the <<OGC19-072,OGC API - Common - Part 1>> document.

The conformance class values defined in this core module are listed in <<conformance_classes_table, Table 1>>.

[[conformance_classes_table]]
.Conformance classes defined in this module.
[width="90%",cols="3,6a",options="header"]
|===
^|*Conformance class* |*URI*
<|<<ats_core,Core>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core
<|<<ats_data_joining,Data joining>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core/data-joining
<|<<ats_file_joining,File joining>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core/file-joining
<|<<ats_join_delete,Join delete>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core/join-delete
<|<<ats_html,HTML>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/html
<|<<ats_json,JSON>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/json
2+|*Input*
<|<<ats_file_uploading,File uploading with Query>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input/file-upload
<|<<ats_file_referencing,File referencing with URL>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input/http-ref
<|<<ats_csv_input,CSV file input>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input/csv
<|<<ats_geojson_input,GeoJSON file input>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input/geojson
2+|*Output*
<|<<ats_geojson,GeoJSON output for joined data>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output/geojson
<|<<ats_geojson_direct,Direct GeoJSON output for joined data>>|http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/output/geojson-direct
|===

In addition, come conformance classes are used from the specifications <<OGC19-072,OGC API - Common - Part 1>> and <<OGC20-024,OGC API - Common - Part 2>>. They are listed in <<ogc_api_common_conformance_classes_table, Table 2>>.

[[ogc_api_common_conformance_classes_table]]
.Conformance classes.
[width="90%",cols="3,6a"]
|===
^|*Conformance class* |*URI*
2+|*OGC API - Common - Part 1*
<|Core|http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core
<|Landing Page|http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landing-page
<|OpenAPI 3.0|http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30
2+|*OGC API - Common - Part 2*
<|Collections|http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections
<|Simple Query|http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query
|===

Conformance with this standard shall be checked using all the relevant tests
specified in <<annex-a,Annex A>> (normative) of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.