== Scope

The OGC API - Joins specifies the behavior of Web APIs that join data from specified input data files either with feature collections that are available on some server or directly with other specified input data files. The core module defines three sets of operation: __discovery operations__, __data joining operations__ and __file joining operations__.

The __discovery operations__ specify operations for obtaining general information on the service implementation of the server that supports a join capability. It includes operations for accessing the Joins API landing page, the API definition document and information on the service’s conformance to the Joins API standard.

The __data joining operations__ specify operations for retrieving metadata and key values on the feature collections available on some server. Data joining also includes an operation for joining data from specified input data files with the feature collections and operations for accessing and deleting the created joins.

The __file joining operations__ specifies an operation for joining data from specified or provided input data files directly with other specified input data files. 

The core module specifies requirements for using CSV and GeoJSON input files. The support for other input file formats may be defined in extension modules.