.Preface

This document defines the core module of the OGC API - Joins standard. The specification is a multi-part document that can be extended by specifying extension modules to the core module.

This document does not suggest any updates to the OGC Abstract Specification

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

This document is the specification for the core module of the OGC API - Joins standard. The core module specifies a service interface that allows attribute data to be joined either with collections that are hosted on the server or directly with inputted files. The core module contains support for CSV and GeoJSON files. The joining of the datasets is executed via common identifiers that are available in both datasets. The OGC API - Joins core module supports also operations for viewing metadata and key values on collections that are available on the server. It contains also operations for accessing and deleting the created joinsd.